# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: vjacks <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/11/22 22:29:13 by vjacks            #+#    #+#              #
#    Updated: 2018/11/23 16:55:29 by vjacks           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FLAGS = -Wall -Wextra -Werror
NAME = ft_display_file

all:
	gcc -c $(FLAGS) ft_display_file.c
	gcc -o $(NAME) ft_display_file.o

clean:
	rm -f *.o

fclean:	clean
	rm -f $(NAME)
